name: Practice project - info
on: issues
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
    - name: Output GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
